### ISSUE TITLE
MongoDb Driver 3.0 Support

### ISSUE THREAD

**Issue by nomz0101** [loresoft/NLog.Mongo#158]
Hi,

Can you please add support for MongoDb Driver 3.0?

After upgrading our project to MongoDb Driver 3.0, writing logs stopped working.
Seems like MongoDb Driver 3.0 is not supported.

Thank you very much.

**Comment by rotem925** [comment]
I have the same exact issue , there some breaking changes with Mongo.Bson. Might be the reason.

**Comment by pwelter34** [comment]
Release in v5.0
