### ISSUE TITLE
How to add HostIp address

### ISSUE THREAD

**Issue by shaair** [loresoft/NLog.Mongo#19]
How to add Host IP address in the configuration?
 Just like 
`<field name="Host" layout="${HostIP}" />`

**Comment by snakefoot** [comment]
You can create custom layout renderer that returns IP-address:

https://github.com/NLog/NLog/wiki/How-to-write-a-custom-layout-renderer

Maybe with inspiration from here (Remember a machine can have multiple IP-address. LAN, WIFI, etc.):

http://carlfranklin.net/blog/2013/12/9/c-to-get-your-local-ip-address-when-online.html

**Comment by snakefoot** [comment]
NLog 4.6.8 introduces `${local-ip}`:

https://github.com/NLog/NLog/wiki/Local-IP-Address-Layout-Renderer
