### ISSUE TITLE
Complete Custom Document duplicate info and properties

### ISSUE THREAD

**Issue by pampua84** [loresoft/NLog.Mongo#20]
Hi,
when i use Complete Custom Document and use field in configuration with layout ${event-properties:MyProperty} , logger writes both fields and properties on database as duplicate.  
![log](https://user-images.githubusercontent.com/17255890/50092756-36488c80-020f-11e9-9dfb-6fc75f1266d1.PNG)

**Comment by snakefoot** [comment]
See also https://stackoverflow.com/questions/53781585/c-sharp-use-nlog-with-mongo

**Comment by snakefoot** [comment]
@pwelter34 Maybe call the property `IncludeEventProperties` to match the logic in other NLog targets:

https://nlog-project.org/documentation/v4.5.0/html/P_NLog_Targets_TargetWithContext_IncludeEventProperties.htm
https://nlog-project.org/documentation/v4.5.0/html/P_NLog_Targets_LogReceiverWebServiceTarget_IncludeEventProperties.htm

Don't mind adding creating a PR

**Comment by snakefoot** [comment]
@pwelter34 Created #23 for review
