### ISSUE TITLE
Connection string from appsetting.json

### ISSUE THREAD

**Issue by ferreira-guilherme** [loresoft/NLog.Mongo#21]
How can I use a conn string from appsettings.json? NLog says that I can do that by using ${configsetting}  like this:

```
<target xsi:type="Mongo"
        name="mongoDefault"
        connectionName=""
        connectionString="${configsetting:DatabaseSettings.ConnString}"
        databaseName="${configsetting:DatabaseSettings.DbName}"
        collectionName="log"
        cappedCollectionSize="26214400">
      <property name="ThreadID" layout="${threadid}" bsonType="Int32" />
      <property name="ThreadName" layout="${threadname}" />
      <property name="ProcessID" layout="${processid}" bsonType="Int32" />
      <property name="ProcessName" layout="${processname:fullName=true}" />
      <property name="UserName" layout="${windows-identity}" />
    </target>
```

But when I run the app I got the following error:

Error Error has been raised. Exception: MongoDB.Driver.MongoConfigurationException: The connection string '${configsetting:DatabaseSettings.ConnString}' is not valid.
   at MongoDB.Driver.Core.Configuration.ConnectionString.Parse()
   at MongoDB.Driver.MongoUrlBuilder.Parse(String url)
   at MongoDB.Driver.MongoUrl..ctor(String url)
   at NLog.Mongo.MongoTarget.<GetCollection>b__46_0(String k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NLog.Mongo.MongoTarget.GetCollection()
   at NLog.Mongo.MongoTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

**Comment by snakefoot** [comment]
Think you are waiting for PR #18 to be merged.

**Comment by ferreira-guilherme** [comment]
Yes. I will wait. Thx

Any date for this to happen?

**Comment by snakefoot** [comment]
@ferreira-guilherme Guess it depends on when @pwelter34 has time to look at #22

**Comment by snakefoot** [comment]
@ferreira-guilherme You can now try ver. `4.5.0.64` from the nuget-DEV-feed:

https://www.myget.org/F/loresoft/

Then you can use `${configsetting}` or `${appsettings}`. See https://www.nuget.org/packages/NLog.Appsettings.Standard/

**Comment by ferreira-guilherme** [comment]
Thx, worked like a charm. Just a note, it worked using NLog.Appsettings.Standard. But it did not work with NLog.Extensions.Logging.
NLog InternalLog:

> 2018-12-19 14:13:59.6908 Info Loading assembly: NLog.Extensions.Logging
> 2018-12-19 14:13:59.7345 Info Loading assembly: NLog.Mongo
> 2018-12-19 14:13:59.9107 Info Adding target File Target[allfile]
> 2018-12-19 14:13:59.9371 Info Adding target File Target[apifile]
> 2018-12-19 14:14:00.0804 Error Error parsing layout configsetting will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'configsetting'
>    at NLog.Config.Factory`2.CreateInstance(String name)
>    at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
> 2018-12-19 14:14:00.0848 Error Error parsing layout configsetting will be ignored. Exception: System.ArgumentException: LayoutRenderer cannot be found: 'configsetting'
>    at NLog.Config.Factory`2.CreateInstance(String name)
>    at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)

**Comment by snakefoot** [comment]
With NLog.Extension.Logging ver. 1.4.0 then you can now use `${configsetting}`

See also: https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer
