### ISSUE TITLE
Missing a Basic NLog / NLog.Mongo Introduction

### ISSUE THREAD

**Issue by MatthiasJost** [loresoft/NLog.Mongo#6]
Just want to say thank you for the NLog.Mongo target. Works as expected now.

I forgot to add:

`<extensions>
  <add assembly="NLog.Mongo"/>
</extensions>`

To NLog.config in the first place.

1. So maybe it would be worth to have a short step-by-step tutorial. It was hard for me to find the error since I am also new to NLog.

2. Is a way to get rid of the schema warning for xsi-type”Mongo”?

**Comment by pwelter34** [comment]
There are examples in the readme.md
