### ISSUE TITLE
BsonString exception thrown when Source is null

### ISSUE THREAD

**Issue by thombrink** [loresoft/NLog.Mongo#67]
An BsonString exception is thrown when Source is null from this line: https://github.com/loresoft/NLog.Mongo/blob/19a7f0bc3cfc51fe0e62ff70c3379098b2418670/src/NLog.Mongo/MongoTarget.cs#L345

Example:
`logger.Error(new Exception("Test"), "Test Exception")`

Will result in an exception.

**Comment by snakefoot** [comment]
Created #68 to resolve this issue

**Comment by snakefoot** [comment]
https://www.nuget.org/packages/NLog.Mongo ver. 4.6.0.161 has been released.
